### ISSUE TITLE
[feature] Add support for myanimelist

### ISSUE THREAD

**Issue by cwrau** [Benexl/FastAnime#19]
As the title says, it would be amazing if you could add support for myanimelist

**Comment by Benex254** [comment]
hmm, thats definitely possible. Instead of anilist it could be myanimelist or sth along those lines. For now you can import myanimelist data on the official anilist website. 
Though i won't be the one doing it. I have written **13k** lines to make this possible **alone** and now i feel its only fair that the community to also contribute.

**Comment by gand0rf** [comment]
Started looking into this. Will take a bit to get it done. My end up needing a couple of people to implement.
